name: release

## Runs all project tests and make sure they all pass.
## Afterwards it builds x86 executables for both Windows and Linux
## and puts them in a release.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          version: 'stable'

      - name: Install dependencies
        run: raco pkg install --auto simple-xlsx

      - name: Test excel functions
        run: raco test excel.rkt

      - name: Test mcnp functions
        run: raco test mcnp

      - name: Create Linux executable
        run: raco exe --embed-dlls -o tally-extract main.rkt
        if: ${{ github.ref_type == 'tag' }}

      - name: Setup Racket cross-compiler
        run: raco pkg install --auto raco-cross
        if: ${{ github.ref_type == 'tag' }}

      - name: Install Windows deps
        run: raco cross --target x86_64-win32 pkg install --auto simple-xlsx
        if: ${{ github.ref_type == 'tag' }}

      - name: Build bytecode for Windows platform
        run: raco cross --target x86_64-win32 make main.rkt
        if: ${{ github.ref_type == 'tag' }}

      - name: Create Windows executable
        run: raco cross --target x86_64-win32 exe -o tally-extract.exe main.rkt
        if: ${{ github.ref_type == 'tag' }}

      - name: Create release with executables attached
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          files: |
            tally-extract
            tally-extract.exe
